name: Build and Push Docker Image

on:
  push:
    paths:
      - package.json
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Fetch the last 2 commits to access HEAD~1

      # Setup Node.js to detect version changes
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      # Extract and compare versions
      - name: Detect version change
        id: detect_version
        run: |
          # Get the current and previous versions from package.json
          CURRENT_VERSION=$(jq -r '.version' package.json)
          PREVIOUS_VERSION=$(git show HEAD~1:package.json | jq -r '.version')

          echo "Current version: $CURRENT_VERSION"
          echo "Previous version: $PREVIOUS_VERSION"

          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "Version upgraded from $PREVIOUS_VERSION to $CURRENT_VERSION."
            echo "version_changed=true" >> $GITHUB_ENV
            echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          else
            echo "No version upgrade detected."
          fi

      # Build the Docker image
      - name: Build Docker image
        if: env.version_changed == 'true'
        run: |
          REPOSITORY=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPOSITORY:${{ env.CURRENT_VERSION }} .

      # Login to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        if: env.version_changed == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push the Docker image
      - name: Push Docker image
        if: env.version_changed == 'true'
        run: |
          REPOSITORY=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$REPOSITORY:${{ env.CURRENT_VERSION }}
